In [3]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 

In [4]:
import os

In [5]:
os.chdir(r"C:\Users\vbaburao\Documents") 

In [6]:
os.getcwd()

'C:\\Users\\vbaburao\\Documents'

In [7]:
data = pd.read_csv('decision.csv')

In [8]:
data.dtypes

Date             object
Covid cases       int64
City traific    float64
sales data      float64
dtype: object

In [9]:
X=data[["City traific","Covid cases"]]


In [10]:
X.astype(int) 

City traific  Covid cases
0              1            2
1              1            2
2              1            4
3              1            8
4              1           14
5              1           19
6              1           25
7              1           30
8              1           34
9              1           52
10             1           76
11             0           98
12             0          121
13             0          200
14             0          234
15             0          291
16             0          428
17             0          621
18             0          964
19             0         1178
20             0         1546
21             0         1891
22             0         2201
23             0         2433
24             0         2915
25             0         3417
26             0         3904
27             0         4256

In [11]:
X=np.array(X)

In [12]:
X.astype(int)

array([[   1,    2],
       [   1,    2],
       [   1,    4],
       [   1,    8],
       [   1,   14],
       [   1,   19],
       [   1,   25],
       [   1,   30],
       [   1,   34],
       [   1,   52],
       [   1,   76],
       [   0,   98],
       [   0,  121],
       [   0,  200],
       [   0,  234],
       [   0,  291],
       [   0,  428],
       [   0,  621],
       [   0,  964],
       [   0, 1178],
       [   0, 1546],
       [   0, 1891],
       [   0, 2201],
       [   0, 2433],
       [   0, 2915],
       [   0, 3417],
       [   0, 3904],
       [   0, 4256]])

In [13]:
Y=data["sales data"]

In [14]:
X.shape

(28, 2)

In [15]:
Y.shape

(28,)

In [16]:

train_size = int(len(X) * 0.66)
X_train, X_test = X[0:train_size], X[train_size:len(X)]
print('Observations: %d' % (len(X)))
print('Training Observations: %d' % (len(X_train)))
print('Testing Observations: %d' % (len(X_test)))

Observations: 28
Training Observations: 18
Testing Observations: 10


In [17]:

train_size = int(len(Y) * 0.66)
Y_train, Y_test = Y[0:train_size], Y[train_size:len(X)]
print('Observations: %d' % (len(Y)))
print('Training Observations: %d' % (len(Y_train)))
print('Testing Observations: %d' % (len(Y_test)))

Observations: 28
Training Observations: 18
Testing Observations: 10


In [18]:
from sklearn.tree import DecisionTreeRegressor  
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train) 

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [19]:
y_pred1 = regressor.predict(X_test)

In [20]:
y_pred1

array([86313335.05, 86313335.05, 86313335.05, 86313335.05, 86313335.05,
       86313335.05, 86313335.05, 86313335.05, 86313335.05, 86313335.05])

In [26]:
test = pd.read_csv('predict_la.csv')

In [27]:
test=np.array(test)

In [28]:
test.astype(int) 

array([[  4579,      0],
       [  5906,      0],
       [  8446,      0],
       [ 12585,      0],
       [ 18249,      0],
       [ 24819,      0],
       [ 33754,      0],
       [ 44555,      0],
       [ 54803,      0],
       [ 67408,      0],
       [ 84934,      0],
       [104469,      0],
       [125363,      0]])

In [29]:
y_pred = regressor.predict(test)

In [30]:
y_pred


array([55970692.24, 55970692.24, 55970692.24, 55970692.24, 55970692.24,
       55970692.24, 55970692.24, 55970692.24, 55970692.24, 55970692.24,
       55970692.24, 55970692.24, 55970692.24])