In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd  

### import os 

In [114]:
os.chdir(r"C:\Users\vbaburao\Documents") 

In [115]:
os.getcwd()

'C:\\Users\\vbaburao\\Documents'

In [179]:
data = pd.read_csv('decision.csv')

In [180]:
data.dtypes

Date             object
Covid cases       int64
City traific    float64
sales data      float64
dtype: object

In [181]:
data.head()

Date  Covid cases  City traific   sales data
0  3/2/2020            2          1.12  58672545.74
1  3/3/2020            2          1.15  61311924.61
2  3/4/2020            4          1.12  61459211.34
3  3/5/2020            8          1.18  60404058.03
4  3/6/2020           14          1.17  61298387.15

In [145]:
data.dtypes

Date            datetime64[ns]
Covid cases              int64
City traific           float64
sales data             float64
dtype: object

In [195]:
df=data.drop('Date',axis=1)

In [196]:
X = df.drop('sales data', axis=1)
y = df['sales data']

In [197]:
X

Covid cases  City traific
0             2          1.12
1             2          1.15
2             4          1.12
3             8          1.18
4            14          1.17
5            19          1.20
6            25          1.05
7            30          1.12
8            34          1.17
9            52          1.13
10           76          1.07
11           98          0.96
12          121          0.88
13          200          0.73
14          234          0.62
15          291          0.45
16          428          0.33
17          621          0.25
18          964          0.19
19         1178          0.17
20         1546          0.17
21         1891          0.13
22         2201          0.11
23         2433          0.12
24         2915          0.11
25         3417          0.12
26         3904          0.12
27         4256          0.12

In [198]:
X.dtypes

Covid cases       int64
City traific    float64
dtype: object

In [199]:
from sklearn.tree import DecisionTreeRegressor  
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y) 

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [201]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [200]:
test = pd.read_csv('predict.csv')

In [172]:
predict= test.drop

Date  Covid cases  City traific
0      1         5724          0.13
1      2         7097          0.09
2      3         7878          0.07
3      4         9690          0.05
4      5        11725          0.04
5      6        13718          0.04
6      7        16462          0.04
7      8        19261          0.04
8      9        21764          0.04
9     10        24594          0.04
10    11        27791          0.04
11    12        31960          0.04
12    13        36754          0.04
13    14        41899          0.04
14    15        46089          0.04
15    16        49822          0.04
16    17        53908          0.04
17    18        57951          0.04
18    19        62761          0.04
19    20        67405          0.04
20    21        71988          0.04
21    22        76884          0.04

In [173]:
y_pred = regressor.predict(test)

In [174]:
y_pred

array([30942419.32, 30942419.32, 30942419.32, 30942419.32, 30942419.32,
       30942419.32, 30942419.32, 30942419.32, 30942419.32, 30942419.32,
       30942419.32, 30942419.32, 30942419.32, 30942419.32, 30942419.32,
       30942419.32, 30942419.32, 30942419.32, 30942419.32, 30942419.32,
       30942419.32, 30942419.32])

In [102]:
X.shape

(28, 2)

In [103]:
X

array([[   2,    1],
       [   2,    1],
       [   4,    1],
       [   8,    1],
       [  14,    1],
       [  19,    1],
       [  25,    1],
       [  30,    1],
       [  34,    1],
       [  52,    1],
       [  76,    1],
       [  98,    0],
       [ 121,    0],
       [ 200,    0],
       [ 234,    0],
       [ 291,    0],
       [ 428,    0],
       [ 621,    0],
       [ 964,    0],
       [1178,    0],
       [1546,    0],
       [1891,    0],
       [2201,    0],
       [2433,    0],
       [2915,    0],
       [3417,    0],
       [3904,    0],
       [4256,    0]])

In [104]:
y = dataset[:, 2].astype(int)  

In [105]:
y.reshape(-1,1)

array([[58672545],
       [61311924],
       [61459211],
       [60404058],
       [61298387],
       [55970692],
       [42934464],
       [62421040],
       [61897499],
       [62903299],
       [71109915],
       [73747569],
       [68038524],
       [53473655],
       [83417505],
       [85737422],
       [90159927],
       [86313335],
       [77182376],
       [66348544],
       [41766549],
       [58017371],
       [47392924],
       [44911032],
       [44024433],
       [47438098],
       [43828672],
       [30942419]])

In [106]:
from sklearn.tree import DecisionTreeRegressor  
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y) 

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [107]:
test = pd.read_csv('predict_la.csv')

In [108]:
test=np.array(test)

In [111]:
test.astype(int) 

array([[  4579,      0],
       [  5906,      0],
       [  8446,      0],
       [ 12585,      0],
       [ 18249,      0],
       [ 24819,      0],
       [ 33754,      0],
       [ 44555,      0],
       [ 54803,      0],
       [ 67408,      0],
       [ 84934,      0],
       [104469,      0],
       [125363,      0]])

In [112]:
y_pred = regressor.predict(test)

In [113]:
y_pred


array([30942419., 30942419., 30942419., 30942419., 30942419., 30942419.,
       30942419., 30942419., 30942419., 30942419., 30942419., 30942419.,
       30942419.])

In [94]:
predicted_df=pd.DataFrame(y_pred)

In [95]:
predicted_df

0
0   30942419.0
1   30942419.0
2   30942419.0
3   30942419.0
4   30942419.0
5   30942419.0
6   30942419.0
7   30942419.0
8   30942419.0
9   30942419.0
10  30942419.0
11  30942419.0
12  30942419.0
13  30942419.0
14  30942419.0
15  30942419.0
16  30942419.0
17  30942419.0
18  30942419.0
19  30942419.0
20  30942419.0
21  30942419.0